services:
  backend-service:
    build: ./backend
    container_name: backend-service
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app  # Mount backend code for live reload
      - /usr/src/app/node_modules  # Anonymous volume to prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: "npx nodemon src/app.js"  # Use nodemon to enable live reload


  frontend-service:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app  # Mount frontend code for live reload
      - /usr/src/app/node_modules  # Anonymous volume to prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: "npm start"


  #blockchain-service:
  #  build: ./blockchain
  #  container_name: blockchain-service
  #  volumes:
  #    - ./blockchain:/usr/src/blockchain
  #  environment:
  #    - ANCHOR_PROVIDER_URL=http://localhost:8899
  #    - ANCHOR_WALLET=/usr/src/blockchain/wallet.json
  #  ports:
  #    - "8899:8899"
  #    - "8900:8900"
  #  logging: 
  #    driver: "none"
