services:
  backend-service:
    build: ./backend
    container_name: backend-service
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
          ignore:
            - node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend-service:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true


  blockchain-service:
    build: ./blockchain
    container_name: blockchain-service
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8899:8899"
      - "8900:8900"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
