[package]
name = "cnft_program"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.26.0"
solana-program = "1.9.9"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
